replicaCount: 2

image:
 repository: wordpress:4.8-apache
 pullPolicy: IfNotPresent

deployment:
 name: wordpress-deployment

service:
 name: wordpress-service
 type: LoadBalancer
 port: 80

resources.requests.cpu: "2500m"
resources.requests.memory: "100Mi"
resources.limits.cpu: "500m"
resources.limits.memory: "512Mi"

